capabilities:
  browserName: 'Chrome'
  browser_version: '105'
  os: 'Windows'
  os_version: '10'
  project: 'Selenium IDE'
  build: 'McKinsey'
  name: 'Sample test'
  browserstack.debug: true
  browserstack.console: 'verbose'
  browserstack.networkLogs: true
server: 'https://BROWSERSTACK_USERNAME:BROWSERSTACK_ACCESS_KEY@hub-cloud.browserstack.com/wd/hub'